[package]
name = "rust-gbe"
version = "0.1.0"
edition = "2024"

[dependencies]
mimalloc = "0.1.47"
minifb = "0.23"

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
debug = "line-tables-only"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "debuginfo"
